image: ruby:3.0.3

before_script:
  - apt-get update -qq && apt-get install -y -qq cargo
  - gem install bundler -v 2.2.32
  - ./bin/setup

stages:
  - lint
  - build
  - test

cache:
  paths:
    - vendor/ruby

build:
  stage: build
  script:
    cargo build --release

rubocop:
  stage: lint
  script:
    - rubocop

rspec:
  stage: test
  script:
    - rake spec
