stages:
  - prepare
  - lint
  - build
  - test

rubocop:
  stage: lint
  image: registry.gitlab.com/gitlab-org/incubation-engineering/real-time-editing/yrb:ruby-3.0.3
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install bundler -v 2.2.32
    - ./bin/setup
  script:
    - rubocop

build-linux-x86:
  stage: build
  image: registry.gitlab.com/gitlab-org/incubation-engineering/real-time-editing/yrb:ruby-3.0.3
  cache:
    paths:
      - target/
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release

rspec:
  stage: test
  script:
    - rake spec
