image: ruby:3.0.3

before_script:
  - gem install bundler -v 2.2.32
  - ./bin/setup

stages:
  - lint
  - build
  - test

cache:
  paths:
    - vendor/ruby

rubocop:
  stage: lint
  script:
    - rubocop

build:
  stage: build
  image: rust:latest
  script:
    cargo build --release
  artifacts:
    paths:
      - target/release

rspec:
  stage: test
  script:
    - rake spec
