stages:
  - lint
  - build
  - test

rubocop:
  stage: lint
  image: ruby:3.0.3
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install bundler -v 2.2.32
    - ./bin/setup
  script:
    - rubocop

build-linux-x86:
  stage: build
  image: rust:latest
  cache:
    paths:
      - target/
  script:
    cargo build --target x86_64-unknown-linux-gnu --release
  artifacts:
    paths:
      - target/release

build-linux-arm:
  stage: build
  image: rust:latest
  cache:
    paths:
      - target/
  script:
    cargo build --target aarch64-unknown-linux-gnu --release
  artifacts:
    paths:
      - target/release

rspec:
  stage: test
  script:
    - rake spec
