variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo

stages:
  - prepare
  - lint
  - build
  - test

rubocop:
  stage: lint
  image: registry.gitlab.com/gitlab-org/incubation-engineering/real-time-editing/yrb:ruby-3.0.3
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install bundler -v 2.2.32
    - ./bin/setup
  script:
    - rubocop

rspec:
  stage: test
  image: registry.gitlab.com/gitlab-org/incubation-engineering/real-time-editing/yrb:ruby-3.0.3
  cache:
    paths:
      - vendor/ruby
  before_script:
    - gem install bundler -v 2.2.32
    - ./bin/setup
  script:
    - rake spec
